In [1]:
import pandas as pd
import sys

# BCB

In [2]:
f1 = 'data/java/bcb_funcs_all.tsv'
data = pd.read_csv(f1, delimiter='\t')

In [3]:
data.columns = ['id', 'code']

In [4]:
data

             id                                               code
0           661      public void convert(File src, File dest) t...
1          1362      public static int[] bubbleSort(int... a) {...
2          1363      public static int[] bubbleSortOtimizado(in...
3          2450      public void process(String dir) {\n       ...
4          6937      public static void main(String[] args) thr...
...         ...                                                ...
59612  23653940      JarAgletClassLoader(URL codebase, Certific...
59613  23655348      public boolean fileCompare(String from, St...
59614  23672349      public static byte[] calculateMD4(byte[] d...
59615  23672350      public static byte[] calculateMD5(byte[] d...
59616  23672354      public static byte[] calculateSHA1(byte[] ...

[59617 rows x 2 columns]

In [5]:
f2 = 'data/java/bcb_pair_ids.pkl'
data_pairs = pd.read_pickle(f2)

In [6]:
data_pairs

            id1       id2 label
0       3024986   3024993     2
1        308643    727183     1
2        308643    587124     1
3        308643    481939     1
4        210006    308643     1
...         ...       ...   ...
97530  20502118  23677111     0
97531   1468160  23677115     0
97532   8232818  23677118     0
97533     98304  23677118     0
97534  22503546  23677112     0

[97535 rows x 3 columns]

In [7]:
d = pd.read_pickle('/Users/konstantinos/Desktop/Clone Generalization/binary files/bcb_1vsAll/data_pairs_all_2000.pickle')

In [8]:
d

,code1,code2,label,functionality_id
0,public void run () {\n try {\n int i...,public void loadSourceCode () {\n int lengt...,1,2
1,public static void doVersionCheck (View view) ...,public static void doVersionCheck (View view) ...,1,2
2,public boolean import_pieces (String filename)...,public static String get (String strUrl) {\n ...,1,2
3,public static BufferedReader getUserSolveStrea...,private static String getDocumentAt (String ur...,1,2
4,public static void doVersionCheck (View view) ...,private String getFanFouMessage (int pageNo) t...,1,2
...,...,...,...,...
37071,void close (HashMap moreInfo) throws IOExcepti...,public static void main (String [] args) {\n ...,0,45
37072,public void createPdf (String filename) throws...,public static void main (String [] args) {\n ...,0,45
37073,public void run () {\n IStructuredSelection...,public static void main (String [] args) {\n ...,0,45
37074,private void initComponents () {\n java.awt...,public static void main (String [] args) {\n ...,0,45
37075,"private void reader (JarFile jar_file, String ...",public static void main (String [] args) {\n ...,0,45

In [15]:
f_all = pd.concat([d['code1'], d['code2']]).unique()

In [18]:
map = {}
for i,f in enumerate(f_all):
    map[f] = i

In [21]:
id1 = []
id2 = []
for i in range(len(d)):
    id1.append(map[d['code1'].iloc[i]])
    id2.append(map[d['code2'].iloc[i]])

In [40]:
f_ids = pd.DataFrame({'id1':id1, 'id2':id2, 'label':d['label'], 'functionality_id':d['functionality_id']})

In [41]:
f_ids

         id1    id2  label  functionality_id
0          0     18      1                 2
1          1      7      1                 2
2          2     25      1                 2
3          3     11      1                 2
4          1     24      1                 2
...      ...    ...    ...               ...
37071  14587  17786      0                45
37072  14588  17786      0                45
37073  14589  17786      0                45
37074  14590  17786      0                45
37075   5385  17786      0                45

[37076 rows x 4 columns]

In [42]:
f_ids.to_pickle('/Users/konstantinos/Desktop/Clone Generalization/binary files/bcb_1vsAll_ASTNN/bcb_pair_ids_1vsRest.pickle')

In [34]:
id = []
code = []
for (k,v) in map.items():
    id.append(v)
    code.append(k)

In [36]:
data_all_df = pd.DataFrame({'id':id, 'code':code})

In [38]:
data_all_df.to_pickle('/Users/konstantinos/Desktop/Clone Generalization/binary files/bcb_1vsAll_ASTNN/bcb_funcs_all_1vsRest.pickle')

# SCB

In [10]:
sys.path.append('../../utilities')
from scb_utilities import get_data_scb

In [11]:
# Get scb data
d_scb = get_data_scb()

In [12]:
# Get bcb data
d_bcb = pd.read_pickle('/Users/konstantinos/Desktop/Clone Generalization/binary files/bcb_1vsAll/data_pairs_all_2000.pickle')

In [14]:
# Concatenate because we want word2vec for both training and test set
d = pd.concat([d_scb, d_bcb])

In [15]:
d

,index,filename,code1,code2,label,functionality_id
0,0.0,Clone277.java,public static boolean isBinaryFile (File f) th...,boolean isBinaryFile (File f) throws IOExcepti...,1,NaN
1,1.0,Clone627.java,public Comparable [] findCommonElements () {\n...,public static Comparable [] findCommonElements...,1,NaN
2,2.0,Clone86.java,public void start (Stage stage) {\n final H...,public void start (Stage primaryStage) {\n ...,1,NaN
3,3.0,Clone69.java,public static void main (String [] args) {\n ...,public static void main (String [] args) {\n ...,1,NaN
4,4.0,Clone332.java,public static void main (String [] args) {\n ...,public static void main (String [] args) {\n ...,1,NaN
...,...,...,...,...,...,...
37071,NaN,NaN,void close (HashMap moreInfo) throws IOExcepti...,public static void main (String [] args) {\n ...,0,45.0
37072,NaN,NaN,public void createPdf (String filename) throws...,public static void main (String [] args) {\n ...,0,45.0
37073,NaN,NaN,public void run () {\n IStructuredSelection...,public static void main (String [] args) {\n ...,0,45.0
37074,NaN,NaN,private void initComponents () {\n java.awt...,public static void main (String [] args) {\n ...,0,45.0
37075,NaN,NaN,"private void reader (JarFile jar_file, String ...",public static void main (String [] args) {\n ...,0,45.0

In [16]:
f_all = pd.concat([d['code1'], d['code2']]).unique()

In [17]:
map = {}
for i,f in enumerate(f_all):
    map[f] = i

In [18]:
id1 = []
id2 = []
for i in range(len(d)):
    id1.append(map[d['code1'].iloc[i]])
    id2.append(map[d['code2'].iloc[i]])

In [25]:
f_ids = pd.DataFrame({'id1':id1, 'id2':id2, 'label':d['label'], 'functionality_id':d['functionality_id']})

In [26]:
f_ids

         id1    id2  label  functionality_id
0          0    687      1               NaN
1          1    688      1               NaN
2          2    689      1               NaN
3          3    690      1               NaN
4          4    658      1               NaN
...      ...    ...    ...               ...
37071  15591  19017      0              45.0
37072  15592  19017      0              45.0
37073  15593  19017      0              45.0
37074  15594  19017      0              45.0
37075   6389  19017      0              45.0

[39076 rows x 4 columns]

In [27]:
f_ids.to_pickle('/Users/konstantinos/Desktop/Clone Generalization/binary files/scb_ASTNN/scb_pair_ids.pickle')

In [22]:
id = []
code = []
for (k,v) in map.items():
    id.append(v)
    code.append(k)

In [23]:
data_all_df = pd.DataFrame({'id':id, 'code':code})

In [24]:
data_all_df.to_pickle('/Users/konstantinos/Desktop/Clone Generalization/binary files/scb_ASTNN/scb_funcs_all.pickle')